# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PFXRouterMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'Nuke'
  pod 'SwiftLint'

  # Pods for PFXRouterMVVM

  target 'PFXRouterMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXRouterMVVMUITests' do
    # Pods for testing
  end

end
